// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTdLPrbg-IHl_gyhmxcGlXZBwjd2eLM8w',
    appId: '1:516791680915:web:a84e4d8c57f92419ebf266',
    messagingSenderId: '516791680915',
    projectId: 'bootcamp-3d9fc',
    authDomain: 'bootcamp-3d9fc.firebaseapp.com',
    storageBucket: 'bootcamp-3d9fc.appspot.com',
    measurementId: 'G-0T1YCTWR50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4H7KJO9vtDlSct9ggT1thLrzLvFhUCg',
    appId: '1:516791680915:android:c126a59c18261b4bebf266',
    messagingSenderId: '516791680915',
    projectId: 'bootcamp-3d9fc',
    storageBucket: 'bootcamp-3d9fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZMawsiAvmoGhCmimJjmcNpM7D97TZ4UY',
    appId: '1:516791680915:ios:e8781413aac8b87aebf266',
    messagingSenderId: '516791680915',
    projectId: 'bootcamp-3d9fc',
    storageBucket: 'bootcamp-3d9fc.appspot.com',
    iosClientId: '516791680915-maoi605pmooms22mkgvu4107tp9f7tpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZMawsiAvmoGhCmimJjmcNpM7D97TZ4UY',
    appId: '1:516791680915:ios:e8781413aac8b87aebf266',
    messagingSenderId: '516791680915',
    projectId: 'bootcamp-3d9fc',
    storageBucket: 'bootcamp-3d9fc.appspot.com',
    iosClientId: '516791680915-maoi605pmooms22mkgvu4107tp9f7tpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
